name: Next.js Versioned CI/CD

# This workflow is triggered only when a tag is pushed
on:
  push:
    tags:
      - 'v*.*.*'  # SemVer pattern, e.g: v1.0.0

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Extract Version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

  deploy:
    needs: prepare
    uses: ./.github/workflows/deploy.yml
    with:
      image_tag: ${{ needs.prepare.outputs.version }}
      docker_tags: ${{ secrets.DOCKERHUB_USERNAME }}/digitalevin-fe:${{ needs.prepare.outputs.version }}
    secrets: inherit