name: Next.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.SHORT_SHA }}
    steps:
      - name: Generate Short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  deploy:
    needs: prepare
    uses: ./.github/workflows/deploy.yml
    with:
      image_tag: ${{ needs.prepare.outputs.short_sha }}
      push_latest: true
    secrets: inherit